import { NextRequest, NextResponse } from 'next/server';
import { GitHubAuthHelper } from '@/lib/github/auth-helper';
import { GitHubRepositoryService } from '@/lib/github/repository';
import { GitOperationsService } from '@/lib/github/git-operations';
import { GitHubRateLimiter } from '@/lib/github/rate-limiter';
import { ScaffoldGenerator } from '@/lib/generator/scaffold-generator';
import { ProgressTracker, progressStore } from '@/lib/generator/progress-tracker';
import type { ScaffoldConfig } from '@/types';
import type { GeneratedFile as GitGeneratedFile } from '@/lib/github/git-operations';

/**
 * POST /api/github/repos/create
 * Create a GitHub repository and push generated scaffold
 */
export async function POST(request: NextRequest) {
  let progressTracker: ProgressTracker | null = null;
  
  try {
    // Get access token and user info
    const accessToken = await GitHubAuthHelper.getAccessToken();
    const user = await GitHubAuthHelper.getCurrentUser();
    
    if (!accessToken || !user) {
      return NextResponse.json(
        { error: 'Not authenticated. Please sign in with GitHub.' },
        { status: 401 }
      );
    }

    // Check rate limit
    const rateLimitCheck = GitHubRateLimiter.checkRateLimit(user.login);
    
    if (!rateLimitCheck.allowed) {
      return NextResponse.json(
        {
          error: 'Rate limit exceeded',
          message: `You can create up to 5 repositories per hour. Please try again in ${GitHubRateLimiter.getTimeUntilReset(rateLimitCheck.resetTime)}.`,
          retryAfter: rateLimitCheck.retryAfter,
          resetTime: rateLimitCheck.resetTime,
        },
        { 
          status: 429,
          headers: {
            'Retry-After': rateLimitCheck.retryAfter?.toString() || '3600',
            'X-RateLimit-Limit': '5',
            'X-RateLimit-Remaining': '0',
            'X-RateLimit-Reset': rateLimitCheck.resetTime.toString(),
          }
        }
      );
    }

    // Parse request body
    const body = await request.json();
    const { name, description, private: isPrivate, config } = body;

    // Validate required fields
    if (!name || typeof name !== 'string') {
      return NextResponse.json(
        { error: 'Repository name is required' },
        { status: 400 }
      );
    }

    if (!config || typeof config !== 'object') {
      return NextResponse.json(
        { error: 'Scaffold configuration is required' },
        { status: 400 }
      );
    }

    // Initialize progress tracker
    const generationId = `github-${Date.now()}-${Math.random().toString(36).substring(7)}`;
    progressStore.create(generationId);
    progressTracker = new ProgressTracker(generationId);

    // Step 1: Create GitHub repository first to get the URL
    progressTracker.update('creating-structure', 'Creating GitHub repository...', 10);
    const scaffoldConfig: ScaffoldConfig = {
      ...config,
      projectName: name,
    };

    const repoService = new GitHubRepositoryService(accessToken);
    
    let repository;
    try {
      repository = await repoService.createRepository({
        name,
        description: description || `Generated by StackForge - ${scaffoldConfig.framework} project`,
        private: isPrivate !== undefined ? isPrivate : false,
        autoInit: false, // We'll push our own files
      });
    } catch (error) {
      if (error instanceof Error) {
        if (error.message.includes('already exists')) {
          return NextResponse.json(
            { 
              error: 'Repository name already exists',
              fallback: 'download',
              generationId,
            },
            { status: 409 }
          );
        }
        throw error;
      }
      throw error;
    }

    progressTracker.update('creating-structure', 'Repository created', 30);

    // Increment rate limit counter after successful repository creation
    GitHubRateLimiter.incrementCount(user.login);

    // Step 2: Generate scaffold files with GitHub repository URL
    progressTracker.update('generating-files', 'Generating scaffold files...', 40);
    const generator = new ScaffoldGenerator(scaffoldConfig);
    const result = await generator.generate(true, repository.htmlUrl);

    progressTracker.update('generating-files', 'Scaffold files generated', 60);

    // Step 3: Convert scaffold files to git format
    progressTracker.update('creating-structure', 'Preparing files for push...', 70);
    const gitFiles: GitGeneratedFile[] = result.files.map(file => ({
      path: file.path,
      content: file.content,
      encoding: 'utf-8' as const,
    }));

    // Step 4: Initialize git and push files
    progressTracker.update('creating-structure', 'Initializing git repository...', 80);
    const gitOps = new GitOperationsService(
      accessToken,
      repository.owner.login,
      repository.name
    );

    // Create initial commit with all files
    progressTracker.update('creating-structure', 'Creating initial commit...', 90);
    const commitMessage = GitOperationsService.generateCommitMessage(scaffoldConfig);
    const author = {
      name: user.name || user.login,
      email: user.email || `${user.login}@users.noreply.github.com`,
    };

    await gitOps.createInitialCommit(gitFiles, author, commitMessage);

    progressTracker.update('creating-structure', 'Files pushed to GitHub', 95);

    // Step 5: Complete
    progressTracker.update('complete', 'Repository created successfully', 100);

    return NextResponse.json({
      success: true,
      repository: {
        id: repository.id,
        name: repository.name,
        fullName: repository.fullName,
        htmlUrl: repository.htmlUrl,
        cloneUrl: repository.cloneUrl,
        sshUrl: repository.sshUrl,
        private: repository.private,
      },
      generationId,
    });

  } catch (error) {
    console.error('Error creating GitHub repository:', error);

    // Mark progress as failed if tracker exists
    if (progressTracker) {
      progressTracker.setError(error instanceof Error ? error.message : 'Unknown error');
    }

    if (error instanceof Error) {
      // Handle specific error cases with detailed messages and retry guidance
      
      // OAuth/Authentication errors
      if (error.message.includes('authentication') || 
          error.message.includes('token') || 
          error.message.includes('Unauthorized') ||
          error.message.includes('401')) {
        return NextResponse.json(
          { 
            error: 'Authentication failed',
            message: 'Your GitHub session has expired. Please sign in again to continue.',
            fallback: 'download',
            canRetry: true,
            retryAction: 'reauthenticate',
          },
          { status: 401 }
        );
      }

      // Rate limit errors (GitHub API)
      if (error.message.includes('rate limit') || 
          error.message.includes('API rate limit exceeded')) {
        return NextResponse.json(
          { 
            error: 'GitHub API rate limit exceeded',
            message: 'GitHub has temporarily limited API requests. Please try again in a few minutes.',
            fallback: 'download',
            canRetry: true,
            retryAfter: 300, // 5 minutes
          },
          { status: 429 }
        );
      }

      // Repository name conflicts
      if (error.message.includes('already exists') || 
          error.message.includes('name already exists')) {
        return NextResponse.json(
          { 
            error: 'Repository name already exists',
            message: 'A repository with this name already exists in your account. Please choose a different name.',
            fallback: 'download',
            canRetry: true,
            retryAction: 'rename',
          },
          { status: 409 }
        );
      }

      // Network timeout errors
      if (error.message.includes('timeout') || 
          error.message.includes('ETIMEDOUT') ||
          error.message.includes('ECONNRESET')) {
        return NextResponse.json(
          { 
            error: 'Network timeout',
            message: 'The request took too long to complete. This might be due to network issues or GitHub being slow.',
            fallback: 'download',
            canRetry: true,
            retryAfter: 30,
          },
          { status: 408 }
        );
      }

      // Network connection errors
      if (error.message.includes('ENOTFOUND') || 
          error.message.includes('ECONNREFUSED') ||
          error.message.includes('network')) {
        return NextResponse.json(
          { 
            error: 'Network error',
            message: 'Unable to connect to GitHub. Please check your internet connection and try again.',
            fallback: 'download',
            canRetry: true,
            retryAfter: 10,
          },
          { status: 503 }
        );
      }

      // Invalid repository name
      if (error.message.includes('invalid') && error.message.includes('name')) {
        return NextResponse.json(
          { 
            error: 'Invalid repository name',
            message: 'The repository name contains invalid characters. Use only letters, numbers, hyphens, and underscores.',
            fallback: 'download',
            canRetry: true,
            retryAction: 'rename',
          },
          { status: 400 }
        );
      }

      // Permission errors
      if (error.message.includes('permission') || 
          error.message.includes('forbidden') ||
          error.message.includes('403')) {
        return NextResponse.json(
          { 
            error: 'Permission denied',
            message: 'You don\'t have permission to create repositories. Please check your GitHub account settings.',
            fallback: 'download',
            canRetry: false,
          },
          { status: 403 }
        );
      }

      // Generic error with message
      return NextResponse.json(
        { 
          error: 'Failed to create repository',
          message: error.message || 'An unexpected error occurred while creating your GitHub repository.',
          fallback: 'download',
          canRetry: true,
          retryAfter: 30,
        },
        { status: 500 }
      );
    }

    // Unknown error
    return NextResponse.json(
      { 
        error: 'Failed to create GitHub repository',
        message: 'An unexpected error occurred. Please try downloading the ZIP file instead.',
        fallback: 'download',
        canRetry: true,
      },
      { status: 500 }
    );
  }
}


